/* tslint:disable */
/* eslint-disable */
/**
 * RareQC Registre Admin API
 * REST API pour le registre québécois de patients atteints de maladies rares — administration.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from "./api";
export * from "./configuration";
